controller_list:
  - name: fake_ms210_arm_controller
    joints:
      - joint_s
      - joint_l
      - joint_u
      - joint_r
      - joint_b
      - joint_t
initial:  # Define initial robot poses.
  - group: ms210_arm
    pose: default_mfg
