# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: ms210_arm
  joint_model_group_pose: default_mfg
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_s
    - joint_l
    - joint_u
    - joint_r
    - joint_b
    - joint_t
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: ms210_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_s
      - joint_l
      - joint_u
      - joint_r
      - joint_b
      - joint_t
