sudo: required
dist: trusty
language: generic

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
  matrix:
    - ROS_DISTRO="indigo" ROS_REPO=ros
    - ROS_DISTRO="indigo" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="kinetic" ROS_REPO=ros
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed

matrix:
  allow_failures:
    - env: ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=ros
    - env: ROS_DISTRO="indigo" ROS_REPOSITORY_PATH=ros-shadow-fixed

install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script: 
  - .ci_config/travis.sh
