# Transforms from base_link to hs_base_link and the inverse. Also includes roll, pitch, yaw representations of rotation for urdfs.
positioner_params:
  headstock_prismatic_offset: 0
  tailstock_revolute_offset: 1.21
  base_to_positioner_tf:
    child_frame_id: hs_base_link
    parent_frame_id: base_link
    translation:
      x: 1.12305
      y: -0.616361
      z: 0.892564
    rotation:
      x: 0.5019611480047158
      y: -0.496654005429208
      z: 0.503338214465581
      w: 0.4980165124205349
      roll: 0
      pitch:  -1.57079632679
      yaw: 1.57079632679
