<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="motoman_gp20hl" params="prefix kinematic_offsets">

    <xacro:include filename="$(find motoman_resources)/urdf/common_materials.xacro"/>

    <!-- link list -->
    <link name="${prefix}base_link">
      <visual>
        <geometry>
          <mesh filename="package://motoman_gp20hl_support/meshes/visual/base_link.stl"/>
        </geometry>
        <xacro:material_yaskawa_blue/>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://motoman_gp20hl_support/meshes/collision/base_link.stl"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_1_s">
      <visual>
        <geometry>
          <mesh filename="package://motoman_gp20hl_support/meshes/visual/link_1_s.stl"/>
        </geometry>
        <xacro:material_yaskawa_blue/>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://motoman_gp20hl_support/meshes/collision/link_1_s.stl"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_2_l">
      <visual>
        <geometry>
          <mesh filename="package://motoman_gp20hl_support/meshes/visual/link_2_l.stl"/>
        </geometry>
        <xacro:material_yaskawa_blue/>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://motoman_gp20hl_support/meshes/collision/link_2_l.stl"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_3_u">
      <visual>
        <geometry>
          <mesh filename="package://motoman_gp20hl_support/meshes/visual/link_3_u.stl"/>
        </geometry>
        <xacro:material_yaskawa_blue/>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://motoman_gp20hl_support/meshes/collision/link_3_u.stl"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_4_r">
      <visual>
        <geometry>
          <mesh filename="package://motoman_gp20hl_support/meshes/visual/link_4_r.stl"/>
        </geometry>
        <xacro:material_yaskawa_blue/>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://motoman_gp20hl_support/meshes/collision/link_4_r.stl"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_5_b">
      <visual>
        <geometry>
          <mesh filename="package://motoman_gp20hl_support/meshes/visual/link_5_b.stl"/>
        </geometry>
        <xacro:material_yaskawa_blue/>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://motoman_gp20hl_support/meshes/collision/link_5_b.stl"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_6_t">
      <visual>
        <geometry>
          <mesh filename="package://motoman_gp20hl_support/meshes/visual/link_6_t.stl"/>
        </geometry>
        <xacro:material_yaskawa_blue/>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://motoman_gp20hl_support/meshes/collision/link_6_t.stl"/>
        </geometry>
      </collision>
    </link>
    <!-- end of link list -->

    <!-- joint list -->
    <!-- Joints are specified such that the driver rotates the joints about the positive Z axis. -->
    <joint name="${prefix}joint_1_s" type="revolute">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}link_1_s"/>
      <origin xyz="${0 + kinematic_offsets['1_s']['x']} ${0 + kinematic_offsets['1_s']['y']} ${0.540 + kinematic_offsets['1_s']['z']}"
              rpy="${0 + kinematic_offsets['1_s']['roll']} ${0 + kinematic_offsets['1_s']['pitch']} ${0 + kinematic_offsets['1_s']['yaw']}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${radians(-180)}" upper="${radians(180)}" effort="3087" velocity="${radians(180)}"/>
    </joint>
    <joint name="${prefix}joint_2_l" type="revolute">
      <parent link="${prefix}link_1_s"/>
      <child link="${prefix}link_2_l"/>
      <origin xyz="${0.145 + kinematic_offsets['2_l']['x']} ${0 + kinematic_offsets['2_l']['y']} ${0 + kinematic_offsets['2_l']['z']}"
              rpy="${0 + kinematic_offsets['2_l']['roll']} ${radians(-90) + kinematic_offsets['2_l']['pitch']} ${radians(-90) + kinematic_offsets['2_l']['yaw']}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${radians(-90)}" upper="${radians(135)}" effort="3087" velocity="${radians(180)}"/>
    </joint>
    <joint name="${prefix}joint_3_u" type="revolute">
      <parent link="${prefix}link_2_l"/>
      <child link="${prefix}link_3_u"/>
      <origin xyz="${1.150 + kinematic_offsets['3_u']['x']} ${0 + kinematic_offsets['3_u']['y']} ${0 + kinematic_offsets['3_u']['z']}"
              rpy="${radians(180) + kinematic_offsets['3_u']['roll']} ${0 + kinematic_offsets['3_u']['pitch']} ${0 + kinematic_offsets['3_u']['yaw']}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${radians(-80)}" upper="${radians(206)}" effort="926.1" velocity="${radians(180)}"/>
    </joint>
    <joint name="${prefix}joint_4_r" type="revolute">
      <parent link="${prefix}link_3_u"/>
      <child link="${prefix}link_4_r"/>
      <origin xyz="${0.250 + kinematic_offsets['4_r']['x']} ${-1.812 + kinematic_offsets['4_r']['y']} ${0 + kinematic_offsets['4_r']['z']}"
              rpy="${radians(-90) + kinematic_offsets['4_r']['roll']} ${0 + kinematic_offsets['4_r']['pitch']} ${0 + kinematic_offsets['4_r']['yaw']}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${radians(-200)}" upper="${radians(200)}" effort="39.2" velocity="${radians(400)}"/>
    </joint>
    <joint name="${prefix}joint_5_b" type="revolute">
      <parent link="${prefix}link_4_r"/>
      <child link="${prefix}link_5_b"/>
      <origin xyz="${0 + kinematic_offsets['5_b']['x']} ${0 + kinematic_offsets['5_b']['y']} ${0 + kinematic_offsets['5_b']['z']}"
              rpy="${radians(90) + kinematic_offsets['5_b']['roll']} ${0 + kinematic_offsets['5_b']['pitch']} ${0 + kinematic_offsets['5_b']['yaw']}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${radians(-150)}" upper="${radians(150)}" effort="39.2" velocity="${radians(435)}"/>
    </joint>
    <joint name="${prefix}joint_6_t" type="revolute">
      <parent link="${prefix}link_5_b"/>
      <child link="${prefix}link_6_t"/>
      <origin xyz="${0 + kinematic_offsets['6_t']['x']} ${-0.1 + kinematic_offsets['6_t']['y']} ${0 + kinematic_offsets['6_t']['z']}"
              rpy="${radians(-90) + kinematic_offsets['6_t']['roll']} ${0 + kinematic_offsets['6_t']['pitch']} ${0 + kinematic_offsets['6_t']['yaw']}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${radians(-210)}" upper="${radians(210)}" effort="19.6" velocity="${radians(700)}"/>
    </joint>
    <!-- end of joint list -->

    <!-- ROS base_link to Robot Manufacturer World Coordinates transform -->
    <link name="${prefix}base"/>
    <joint name="${prefix}base_link-base" type="fixed">
      <origin xyz="0 0 0.540" rpy="0 0 0"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}base"/>
    </joint>

    <!-- ROS-Industrial 'flange' frame: attachment point for EEF models -->
    <link name="${prefix}flange"/>
    <joint name="${prefix}joint_6_t-flange" type="fixed">
      <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
      <parent link="${prefix}link_6_t"/>
      <child link="${prefix}flange"/>
    </joint>

    <!-- ROS-Industrial 'tool0' frame: all-zeros tool frame -->
    <link name="${prefix}tool0"/>
    <joint name="${prefix}flange-tool0" type="fixed">
      <origin xyz="0 0 0" rpy="${pi} ${-pi/2.0} 0"/>
      <parent link="${prefix}flange"/>
      <child link="${prefix}tool0"/>
    </joint>

  </xacro:macro>
</robot>

