
# Read (and return) the current value of the IO element at 'address'.
#
# Addresses are plain, base-10 integers, as used and displayed by the controller
# (on the teach pendant for instance).
#
# There are no restrictions as to which IO elements can be read, but they have
# to exist on the controller and be configured correctly.
#
# Refer also the Yaskawa Motoman documentation on IO addressing and
# configuration.

uint32 address
---
string message
bool success
int32 value
