
# Read (and return) the current value of the M register at 'address'.
#
# Addresses are plain, base-10 integers, as used and displayed by the controller
# (on the teach pendant for instance).
#
# Only the following addresses can be read from:
#
#  - 0 to 999
#
# NOTE 1: do not add 1000000 to the address, MotoROS will do this when
#         necessary.
#
# NOTE 2: many programming languages will parse literals starting with '0' as
#         octal numbers. Do not add leading zeros to register addresses to avoid
#         specifying the wrong register to read.
#
# Refer also the Yaskawa Motoman documentation on IO addressing and
# configuration.

uint32 address
---
string message
bool success
uint16 value
