
# Write 'value' to the Group IO element at 'address'.
#
# Addresses are plain, base-10 integers, as used and displayed by the controller
# (on the teach pendant for instance).
#
# Only the following addresses can be written to:
#
#  - 2701 and up : Network Inputs (2501 and up on DX100 and FS100)
#  - 1001 and up : Universal/General Outputs
#
# NOTE: many programming languages will parse literals starting with '0' as
#       octal numbers. Do not add leading zeros to group addresses to avoid
#       specifying the wrong address to write to.

# Refer also the Yaskawa Motoman documentation on IO addressing and
# configuration.

uint32 address
uint8 value
---
string message
bool success
