# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  ma1440_joint_b:
    has_velocity_limits: true
    max_velocity: 7.50492
    has_acceleration_limits: false
    max_acceleration: 0
  ma1440_joint_l:
    has_velocity_limits: true
    max_velocity: 3.49066
    has_acceleration_limits: false
    max_acceleration: 0
  ma1440_joint_r:
    has_velocity_limits: true
    max_velocity: 7.50492
    has_acceleration_limits: false
    max_acceleration: 0
  ma1440_joint_s:
    has_velocity_limits: true
    max_velocity: 4.01425727959
    has_acceleration_limits: false
    max_acceleration: 0
  ma1440_joint_t:
    has_velocity_limits: true
    max_velocity: 10.9956
    has_acceleration_limits: false
    max_acceleration: 0
  ma1440_joint_u:
    has_velocity_limits: true
    max_velocity: 4.01425727959
    has_acceleration_limits: false
    max_acceleration: 0
  mh185_vertical_joint_1:
    has_velocity_limits: true
    max_velocity: 1.15
    has_acceleration_limits: false
    max_acceleration: 0