cell_parameters:
  positioner_parameters:
    #model_id corresponds to the PositionerModels int of the positioner for this cell found in forge_definitions/forge_positioners.
    model_id: 2 # 2 is the model number for motoman_motopos_d500
#  arm_parameters:
  # Not currently used/implemented
  #    model_id: