topic_list:
    - name: arm_controller
      ns: dx200
      group: 0
      joints: ['joint_s','joint_l','joint_u','joint_r','joint_b','joint_t']
    - name: positioner_controller
      ns: dx200
      group: 1
      joints: ['joint_1','joint_2']    