joint_limits:
  joint_s:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.66
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  joint_l:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.66
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  joint_e:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.96
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  joint_u:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 2.96
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  joint_r:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.48
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  joint_b:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 3.48
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false
  joint_t:
    has_position_limits: true
    has_velocity_limits: true
    max_velocity: 6.97
    has_acceleration_limits: true
    max_acceleration: 1
    angle_wraparound: false