multi_dof_joints:
  - name: world_joint
    type: Floating
    parent_frame_id: base_link
    child_frame_id: base_link
groups:
  - name: manipulator
    base_link: base_link
    tip_link: link_t
default_collision_operations:
  - object1: base_link
    object2: link_s
    operation: disable  # Adjacent in collision
  - object1: link_s
    object2: link_l
    operation: disable  # Adjacent in collision
  - object1: link_l
    object2: link_e
    operation: disable  # Adjacent in collision
  - object1: link_e
    object2: link_u
    operation: disable  # Adjacent in collision
  - object1: link_u
    object2: link_r
    operation: disable  # Adjacent in collision
  - object1: link_r
    object2: link_b
    operation: disable  # Adjacent in collision
  - object1: link_b
    object2: link_t
    operation: disable  # Adjacent in collision
  - object1: base_link
    object2: link_b
    operation: disable  # Occasionally in collision
  - object1: base_link
    object2: link_r
    operation: disable  # Occasionally in collision
  - object1: base_link
    object2: link_t
    operation: disable  # Occasionally in collision
  - object1: base_link
    object2: link_u
    operation: disable  # Occasionally in collision
  - object1: link_b
    object2: link_l
    operation: disable  # Occasionally in collision
  - object1: link_b
    object2: link_s
    operation: disable  # Occasionally in collision
  - object1: link_e
    object2: link_r
    operation: disable  # Occasionally in collision
  - object1: link_l
    object2: link_r
    operation: disable  # Occasionally in collision
  - object1: link_l
    object2: link_t
    operation: disable  # Occasionally in collision
  - object1: link_l
    object2: link_u
    operation: disable  # Occasionally in collision
  - object1: link_r
    object2: link_s
    operation: disable  # Occasionally in collision
  - object1: link_s
    object2: link_t
    operation: disable  # Occasionally in collision
  - object1: base_link
    object2: link_e
    operation: disable  # Never in collision
  - object1: base_link
    object2: link_l
    operation: disable  # Never in collision
  - object1: link_b
    object2: link_e
    operation: disable  # Never in collision
  - object1: link_b
    object2: link_u
    operation: disable  # Never in collision
  - object1: link_e
    object2: link_s
    operation: disable  # Never in collision
  - object1: link_e
    object2: link_t
    operation: disable  # Never in collision
  - object1: link_r
    object2: link_t
    operation: disable  # Never in collision
  - object1: link_s
    object2: link_u
    operation: disable  # Never in collision
  - object1: link_t
    object2: link_u
    operation: disable  # Never in collision