controller_list:
  - name: ma1440_d500
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_s
      - joint_l
      - joint_u
      - joint_r
      - joint_b
      - joint_t
    allowed_execution_duration_scaling: 2.0