# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1
    - joint_2
    - joint_s
    - joint_l
    - joint_u
    - joint_r
    - joint_b
    - joint_t
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_controller:
  type: position_controllers/JointPositionController
  joints:
    - joint_s
    - joint_l
    - joint_u
    - joint_r
    - joint_b
    - joint_t
  gains:
    joint_s:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_u:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_b:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1