# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_b:
    has_velocity_limits: true
    max_velocity: 2.967
    has_acceleration_limits: false
    max_acceleration: 0
  joint_l:
    has_velocity_limits: true
    max_velocity: 2.967
    has_acceleration_limits: false
    max_acceleration: 0
  joint_s:
    has_velocity_limits: true
    max_velocity: 2.967
    has_acceleration_limits: false
    max_acceleration: 0
  joint_t:
    has_velocity_limits: true
    max_velocity: 6.108
    has_acceleration_limits: false
    max_acceleration: 0
  joint_u:
    has_velocity_limits: true
    max_velocity: 2.967
    has_acceleration_limits: false
    max_acceleration: 0