<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
<xacro:macro
    name="motoman_motopos_d500"
    params="prefix world_base_xyz:='0 0 0'
    world_base_rpy:='0 0 0'
    table_thickness:=0
    offsets_file_path"
>
  <xacro:property name="M_PI" value="3.1415926535897931"/>

  <xacro:property name="offsets" value="${load_yaml(offsets_file_path)[prefix + 'robot_calibration_offsets']}"/>

  <!-- link list -->
  <link name="${prefix}base_link">
    <visual>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/visual/base_link.stl"/>
      </geometry>
      <material name="yaskawa_blue"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/collision/base_link.stl"/>
      </geometry>
    </collision>
  </link>
  <link name="${prefix}link_1">
    <visual>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/visual/link_1.stl"/>
      </geometry>
      <material name="yaskawa_blue"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/collision/link_1.stl"/>
      </geometry>
    </collision>
  </link>
  <link name="${prefix}link_2">
    <visual>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/visual/link_2.stl"/>
      </geometry>
      <material name="yaskawa_blue"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/collision/link_2.stl"/>
      </geometry>
    </collision>
  </link>
  <link name="${prefix}tool0">
    <visual>
      <geometry>
          <cylinder length="${table_thickness}" radius="0.5" />
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0 " />
      <material name="Cast Carbon Steel">
        <color rgba="0.52941 0.54902 0.54902 1" />
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${table_thickness}" radius="0.5" />
      </geometry>
    </collision>  
  </link>
  <!-- this is here to set a base link in the URDF to link the "positioner/base" frame to for scanning -->
  <link name="positioner/base"/>
  <!-- this is here to set a base link in the URDF to link the "positioner/center" frame to for scanning. this is equivalent to the tool frame
  in this case, but we define this so that the naming is consistent across positioner setups -->
  <link name="positioner/center"/>
  <!-- end of link list -->

  <!-- joint list -->
  <joint name="${prefix}world-base" type="fixed">
      <origin xyz="${world_base_xyz}" rpy="${world_base_rpy}"/>
      <parent link="world" />
      <child link="${prefix}base_link"/>
  </joint>
  <joint name="${prefix}joint_1" type="revolute">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}link_1"/>
    <origin xyz="0 0 0.380" rpy="0 0 0" />
    <axis xyz="0 -1 0" />
    <limit lower="-2.3561" upper="2.3561" effort="1274" velocity="1.3962"/>
  </joint>
  <xacro:transmission_macro name="1"/>
  <joint name="${prefix}joint_2" type="revolute">
    <parent link="${prefix}link_1"/>
    <child link="${prefix}link_2"/>
    <origin
        xyz=
            "${offsets[prefix + 'joint_2']['x']}
             ${offsets[prefix + 'joint_2']['y']}
             ${offsets[prefix + 'joint_2']['z']}"
        rpy=
            "${offsets[prefix + 'joint_2']['roll']}
             ${offsets[prefix + 'joint_2']['pitch']}
             ${offsets[prefix + 'joint_2']['yaw']}"/>
    <axis xyz="0 0 -1" />
    <limit lower="-3.4906" upper="3.4906" effort="392" velocity="2.7925"/>
  </joint>
  <xacro:transmission_macro name="2"/>
  <joint name="${prefix}joint_2-tool0" type="fixed">
    <origin xyz="0 0 ${0.165}" rpy="0 0 0"/>
    <parent link="${prefix}link_2"/>
    <child link="${prefix}tool0"/>
  </joint>
  <xacro:transmission_macro name="2"/>
  <joint name="positioner/base" type="fixed">
    <origin
        xyz=
            "${offsets[prefix + 'joint_2']['x']}
             ${offsets[prefix + 'joint_2']['y']}
             ${offsets[prefix + 'joint_2']['z'] + 0.165 + table_thickness}"
        rpy=
            "${offsets[prefix + 'joint_2']['roll']}
             ${offsets[prefix + 'joint_2']['pitch']}
             ${offsets[prefix + 'joint_2']['yaw']}"/>
    <parent link="${prefix}link_1"/>
    <child link="positioner/base"/>
  </joint>
  <joint name="positioner/center" type="fixed">
    <origin xyz="0 0 ${table_thickness}" rpy="0 0 0"/>
    <parent link="${prefix}tool0"/>
    <child link="positioner/center"/>
  </joint>
  <!-- end of joint list -->

  <!-- ROS base_link to Robot Manufacturer World Coordinates transform -->
  <link name="${prefix}base" />
  <joint name="${prefix}base_link-base" type="fixed">
    <origin xyz="0 0 0.380" rpy="0 0 0"/>
    <parent link="${prefix}base_link"/>
    <child link="${prefix}base"/>
  </joint>

  </xacro:macro>
</robot>
