<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
<xacro:property name="world_base_xyz" value="0 0 0"/>
<xacro:property name="world_base_rpy" value="0 0 0"/>
<!-- offsets tool and positioner base/center frames to account for added tabletop -->
<xacro:property name="table_thickness" default="0"/>
<xacro:macro name="motoman_motopos_d500" params="prefix world_base_xyz:=^ world_base_rpy:=^ table_thickness:=^">

  <!-- link list -->
  <link name="${prefix}base_link">
    <visual>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/visual/base_link.stl"/>
      </geometry>
      <material name="yaskawa_blue"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/collision/base_link.stl"/>
      </geometry>
    </collision>
  </link>
  <link name="${prefix}link_1">
    <visual>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/visual/link_1.stl"/>
      </geometry>
      <material name="yaskawa_blue"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/collision/link_1.stl"/>
      </geometry>
    </collision>
  </link>
  <link name="${prefix}link_2">
    <visual>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/visual/link_2.stl"/>
      </geometry>
      <material name="yaskawa_blue"/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/collision/link_2.stl"/>
      </geometry>
    </collision>
  </link>
  <link name="${prefix}tool0"/>
  <!-- this is here to set a base link in the URDF to link the "positioner/base" frame to for scanning -->
  <link name="positioner_base_dummy_link"/>
  <!-- this is here to set a base link in the URDF to link the "positioner/center" frame to for scanning. this is equivalent to the tool frame
  in this case, but we define this so that the naming is consistent across positioner setups -->
  <link name="positioner_center_dummy_link"/>  
  <!-- end of link list -->

  <!-- joint list -->
  <joint name="${prefix}world-base" type="fixed">
      <origin xyz="${world_base_xyz}" rpy="${world_base_rpy}"/>
      <parent link="world" />
      <child link="${prefix}base_link"/>
  </joint>
  <joint name="${prefix}joint_1" type="revolute">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}link_1"/>
    <origin xyz="0 0 0.380" rpy="0 0 0" />
    <axis xyz="0 -1 0" />
    <limit lower="-2.3561" upper="2.3561" effort="1274" velocity="1.3962"/>
  </joint>
  <xacro:transmission_macro name="1"/>
  <joint name="${prefix}joint_2" type="revolute">
    <parent link="${prefix}link_1"/>
    <child link="${prefix}link_2"/>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <axis xyz="0 0 1" />
    <limit lower="-3.4906" upper="3.4906" effort="392" velocity="2.7925"/>
  </joint>
  <xacro:transmission_macro name="2"/>
  <joint name="${prefix}joint_2-tool0" type="fixed">
    <origin xyz="0 0 ${0.150 + table_thickness}" rpy="0 0 0"/>
    <parent link="${prefix}link_2"/>
    <child link="${prefix}tool0"/>
  </joint>
  <xacro:transmission_macro name="2"/>
  <joint name="positioner_base_dummy_joint" type="fixed">
    <origin xyz="0 0 ${0.150 + table_thickness}" rpy="0 0 0"/>
    <parent link="${prefix}link_1"/>
    <child link="positioner_base_dummy_link"/>
  </joint>
  <joint name="positioner_center_dummy_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="${prefix}tool0"/>
    <child link="positioner_center_dummy_link"/>
  </joint>    
  <!-- end of joint list -->

  <!-- ROS base_link to Robot Manufacturer World Coordinates transform -->
  <link name="${prefix}base" />
  <joint name="${prefix}base_link-base" type="fixed">
    <origin xyz="0 0 0.380" rpy="0 0 0"/>
    <parent link="${prefix}base_link"/>
    <child link="${prefix}base"/>
  </joint>

  </xacro:macro>
</robot>
