<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
<xacro:macro name="motoman_motopos_d500" params="prefix kinematic_offsets">

  <xacro:include filename="$(find motoman_resources)/urdf/common_materials.xacro"/>

  <!-- link list -->
  <link name="${prefix}base_link">
    <visual>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/visual/base_link.stl"/>
      </geometry>
      <xacro:material_yaskawa_blue/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/collision/base_link.stl"/>
      </geometry>
    </collision>
  </link>
  <link name="${prefix}link_1">
    <visual>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/visual/link_1.stl"/>
      </geometry>
      <xacro:material_yaskawa_blue/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/collision/link_1.stl"/>
      </geometry>
    </collision>
  </link>
  <link name="${prefix}link_2">
    <visual>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/visual/link_2.stl"/>
      </geometry>
      <xacro:material_yaskawa_blue/>
    </visual>
    <collision>
      <geometry>
        <mesh filename="package://motoman_motopos_d500_support/meshes/motopos_d500/collision/link_2.stl"/>
      </geometry>
    </collision>
  </link>
  <link name="${prefix}flange"/>
  <link name="${prefix}tool0"/>
  <!-- end of link list -->

  <!-- joint list -->
  <joint name="${prefix}joint_1" type="revolute">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}link_1"/>
    <origin xyz="${0 + kinematic_offsets['link_1']['x']} ${0 + kinematic_offsets['link_1']['y']} ${0.380 + kinematic_offsets['link_1']['z']}"
            rpy="${0 + kinematic_offsets['link_1']['roll']} ${0 + kinematic_offsets['link_1']['pitch']} ${0 + kinematic_offsets['link_1']['yaw']}" />
    <axis xyz="0 -1 0" />
    <limit lower="-2.3561" upper="2.3561" effort="1274" velocity="1.3962"/>
  </joint>
  <joint name="${prefix}joint_2" type="revolute">
    <parent link="${prefix}link_1"/>
    <child link="${prefix}link_2"/>
    <origin xyz="${0 + kinematic_offsets['link_2']['x']} ${0 + kinematic_offsets['link_2']['y']} ${0 + kinematic_offsets['link_2']['z']}"
            rpy="${0 + kinematic_offsets['link_2']['roll']} ${0 + kinematic_offsets['link_2']['pitch']} ${0 + kinematic_offsets['link_2']['yaw']}" />
    <axis xyz="0 0 -1" />
    <limit lower="-10" upper="10" effort="392" velocity="2.7925"/>
  </joint>

  <joint name="${prefix}joint_2-flange" type="fixed">
    <origin xyz="0 0 0.150" rpy="0 ${-pi/2} 0"/>
    <parent link="${prefix}link_2"/>
    <child link="${prefix}flange"/>
  </joint>

  <joint name="${prefix}flange-tool0" type="fixed">
    <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
    <parent link="${prefix}flange"/>
    <child link="${prefix}tool0"/>
  </joint>
  <!-- end of joint list -->

  <!-- ROS base_link to Robot Manufacturer World Coordinates transform -->
  <link name="${prefix}base" />
  <joint name="${prefix}base_link-base" type="fixed">
    <origin xyz="0 0 0.380" rpy="0 0 0"/>
    <parent link="${prefix}base_link"/>
    <child link="${prefix}base"/>
  </joint>

  </xacro:macro>
</robot>
